#!/bin/sh
####################################################################################################
# AUTH: Matthew Baum
# DESC: This script automates the execution of a jmeter test and the production of test results
# ARGS:
#	$1: working directory
#   $2: script name: JMX file to run
#   $others: All other arguments are forwarded directly to jmeter
#
# NOTE: This script assumes jmeter is included in the command path
####################################################################################################
set -e

if [ $# -lt 2 ]
then
	echo "**** ERROR: Must pass at least 1 args to this script: 1=working directory 2=script name"
	echo "\tFound $# args: #@"
	echo "\texiting..."
	exit 1
fi

workdir="$1"
jmx="$2"
shift 2

# create output directory
DATETIME=$(date +"%Y-%m-%d_%H-%M-%S")
RES_DIR="$workdir/res/$DATETIME"
echo "**** LOG: Results will appear under: $RES_DIR"
mkdir -p $RES_DIR

# run test and save console log
echo "**** LOG: Starting jmeter test: $jmx"
echo "**** LOG: Additional arguments: $@"
jmeter -n -t "$workdir/$jmx" -l $RES_DIR/res.csv -e -o $RES_DIR/dashboard -j $RES_DIR/jmeter.log -JRES_DIR=$RES_DIR $@ | tee $RES_DIR/console.log
